export const INITIALIZE_USER = "INITIALIZE_USER";
export const INITIALIZE_CONTROLS = "INITIALIZE_CONTROLS";
export const INITIALIZE_USER_FAIL = "INITIALIZE_USER_FAIL";
export const CLOSE_MODAL = "CLOSE_MODAL";

// CONTROLS ACTIONS

export const UPDATE_CONTROLS_START = "UPDATE_CONTROLS_START";
export const UPDATE_LED_STATE = "UPDATE_LED_STATE";
export const UPDATE_CONTROLS_FINISH = "UPDATE_CONTROLS_FINISH";
export const UPDATE_SERVO = "UPDATE_SERVO";
export const UPDATE_SERVO_AFTER_SEQ = "UPDATE_SERVO_AFTER_SEQ";

export const CONTROLLER_BUSY_START = "CONTROLLER_BUSY_START";
export const CONTROLLER_BUSY_END = "CONTROLLER_BUSY_END";
export const CONTROLLER_ERROR = "CONTROLLER_ERROR";
export const CONTROLLER_ERROR_MODAL_CLOSE = "CONTROLLER_ERROR_MODAL_CLOSE";

// SEQUENCE ACTIONS

export const ADD_NEW_SEQUENCE_TOGGLE = "ADD_NEW_SEQUENCE_TOGGLE";
export const ADD_NEW_SEQUENCE_ELEMENT = "ADD_NEW_SEQUENCE_ELEMENT";
export const SAVE_NEW_SEQUENCE = "SAVE_NEW_SEQUENCE";
export const INITIALIZE_SEQUENCE = "INITIALIZE_SEQUENCE";
export const DELETE_SEQUENCE = "DELETE_SEQUENCE";
